server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: car
          uri: lb://car
          predicates:
            - Path=/car/**
          filters:
            - RewritePath=/car/(?<path>.*), /$\{path}
        - id: search
          uri: lb://search
          predicates:
            - Path=/search/**
          filters:
            - RewritePath=/search/(?<path>.*), /$\{path}
        - id: zahtev
          uri: lb://zahtev
          predicates:
            - Path=/zahtev/**
          filters:
            - RewritePath=/zahtev/(?<path>.*), /$\{path}
