version: '3.7'
services:

  consul-server:
    image: consul-server
    build:
      context: ./consul-server
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8500:8500"
    restart: on-failure 
    networks:
      static-network:
        ipv4_address: 172.20.0.2

  rabbitmq-broker:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - static-network

#  mysql-backend:
#    image: mysql:8.0.19
#    environment:
#      MYSQL_ROOT_PASSWORD: fakultet
#      MYSQL_USER: root
#      MYSQL_PASSWORD: fakultet
#      MYSQL_DATABASE: xml_backend
#    ports:
#      - "3306"  
#    restart: always  
#    container_name: mysql-backend
#    networks:
##      - static-network  
#   volumes:
#      - mysql-data:/var/lib/mysql  

  adnin-service:
    image: adnin-service
    environment:
#        DATABASE_USERNAME: root
#        DATABASE_PASSWORD: fakultet
#        DATABASE_SCHEMA: xml_user_service
#        DATABASE_DOMAIN: mysql-backend
#        DATABASE_PORT: 3306
        RMQ_HOST: rabbitmq-broker
    build:
      context: ./services/adnin-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    restart: on-failure 
    depends_on:
      - consul-server
#      - mysql-backend
      - rabbitmq-broker


  vozilo-service:
    image: vozilo-service
    environment:
#        DATABASE_USERNAME: root
#        DATABASE_PASSWORD: fakultet
#        DATABASE_SCHEMA: xml_car_service
#        DATABASE_DOMAIN: mysql-backend
#        DATABASE_PORT: 3306
        RMQ_HOST: rabbitmq-broker
    build:
      context: ./services/vozilo-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    restart: on-failure 
    depends_on:
      - consul-server
#      - mysql-backend
      - rabbitmq-broker

  search-service:
    image: search-service
    environment:
#        DATABASE_USERNAME: root
#        DATABASE_PASSWORD: fakultet
#        DATABASE_SCHEMA: xml_search_service
#        DATABASE_DOMAIN: mysql-backend
#        DATABASE_PORT: 3306
        RMQ_HOST: rabbitmq-broker
    build:
      context: ./services/search-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    restart: on-failure 
    depends_on:
      - consul-server
#      - mysql-backend
      - rabbitmq-broker

  zahtev-sevices:
    image: zahtev-sevices
    environment:
#        DATABASE_USERNAME: root
#        DATABASE_PASSWORD: fakultet
#        DATABASE_SCHEMA: xml_request_service
#        DATABASE_DOMAIN: mysql-backend
#        DATABASE_PORT: 3306
        RMQ_HOST: rabbitmq-broker
    build:
      context: ./services/zahtev-sevices
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    restart: on-failure 
    depends_on:
      - consul-server
#      - mysql-backend
      - rabbitmq-broker
 
  gateway:
    image: gateway
    build:
      context: ./services/Gateway
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8080:8080"
    networks:
      - static-network
    restart: on-failure 
    depends_on:
      - consul-server
      








volumes:
  mysql-data:
  
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
