version: '3'
services:

  consul-server:
    image: consul-server
    build:
      context: ./consul-server
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8500:8500"
    networks:
      static-network:
        ipv4_address: 172.20.0.2

  adnin-service:
    image: adnin-service
    build:
      context: ./services/adnin-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server


  vozilo-service:
    image: vozilo-service
    build:
      context: ./services/vozilo-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  search-service:
    image: search-service
    build:
      context: ./services/search-service
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server

  zahtev-sevices:
    image: zahtev-sevices
    build:
      context: ./services/zahtev-sevices
      dockerfile: Dockerfile
    tty: true
    networks:
      - static-network
    depends_on:
      - consul-server
 
  gateway:
    image: gateway
    build:
      context: ./services/Gateway
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8080:8080"
    networks:
      - static-network
    depends_on:
      - consul-server








networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
