//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 01:06:03 PM CEST 
//


package com.example.voziloservice.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.voziloservice.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.voziloservice.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PostProbaRequest }
     * 
     */
    public PostProbaRequest createPostProbaRequest() {
        return new PostProbaRequest();
    }

    /**
     * Create an instance of {@link PostProbaResponse }
     * 
     */
    public PostProbaResponse createPostProbaResponse() {
        return new PostProbaResponse();
    }

    /**
     * Create an instance of {@link PostVoziloRequest }
     * 
     */
    public PostVoziloRequest createPostVoziloRequest() {
        return new PostVoziloRequest();
    }

    /**
     * Create an instance of {@link Vozilo }
     * 
     */
    public Vozilo createVozilo() {
        return new Vozilo();
    }

    /**
     * Create an instance of {@link PostVoziloResponse }
     * 
     */
    public PostVoziloResponse createPostVoziloResponse() {
        return new PostVoziloResponse();
    }

    /**
     * Create an instance of {@link UpdateVoziloRequset }
     * 
     */
    public UpdateVoziloRequset createUpdateVoziloRequset() {
        return new UpdateVoziloRequset();
    }

    /**
     * Create an instance of {@link UpdateVoziloResponse }
     * 
     */
    public UpdateVoziloResponse createUpdateVoziloResponse() {
        return new UpdateVoziloResponse();
    }

    /**
     * Create an instance of {@link GetZahteveByIzdavacMailRequset }
     * 
     */
    public GetZahteveByIzdavacMailRequset createGetZahteveByIzdavacMailRequset() {
        return new GetZahteveByIzdavacMailRequset();
    }

    /**
     * Create an instance of {@link GetZahteveByIzdavacMailResponse }
     * 
     */
    public GetZahteveByIzdavacMailResponse createGetZahteveByIzdavacMailResponse() {
        return new GetZahteveByIzdavacMailResponse();
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link GetMailUlogovanogAgentaRequest }
     * 
     */
    public GetMailUlogovanogAgentaRequest createGetMailUlogovanogAgentaRequest() {
        return new GetMailUlogovanogAgentaRequest();
    }

    /**
     * Create an instance of {@link GetMailUlogovanogAgentaResponse }
     * 
     */
    public GetMailUlogovanogAgentaResponse createGetMailUlogovanogAgentaResponse() {
        return new GetMailUlogovanogAgentaResponse();
    }

    /**
     * Create an instance of {@link GetMailPodnosiocaRequest }
     * 
     */
    public GetMailPodnosiocaRequest createGetMailPodnosiocaRequest() {
        return new GetMailPodnosiocaRequest();
    }

    /**
     * Create an instance of {@link GetMailPodnosiocaResponse }
     * 
     */
    public GetMailPodnosiocaResponse createGetMailPodnosiocaResponse() {
        return new GetMailPodnosiocaResponse();
    }

    /**
     * Create an instance of {@link PostChatRequest }
     * 
     */
    public PostChatRequest createPostChatRequest() {
        return new PostChatRequest();
    }

    /**
     * Create an instance of {@link Chat }
     * 
     */
    public Chat createChat() {
        return new Chat();
    }

    /**
     * Create an instance of {@link PostChatResponse }
     * 
     */
    public PostChatResponse createPostChatResponse() {
        return new PostChatResponse();
    }

    /**
     * Create an instance of {@link PostMessageRequest }
     * 
     */
    public PostMessageRequest createPostMessageRequest() {
        return new PostMessageRequest();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link PostMessageResponse }
     * 
     */
    public PostMessageResponse createPostMessageResponse() {
        return new PostMessageResponse();
    }

    /**
     * Create an instance of {@link GetChatByAgentMailRequest }
     * 
     */
    public GetChatByAgentMailRequest createGetChatByAgentMailRequest() {
        return new GetChatByAgentMailRequest();
    }

    /**
     * Create an instance of {@link GetChatByAgentMailResponse }
     * 
     */
    public GetChatByAgentMailResponse createGetChatByAgentMailResponse() {
        return new GetChatByAgentMailResponse();
    }

    /**
     * Create an instance of {@link GetMessageByChatIdRequest }
     * 
     */
    public GetMessageByChatIdRequest createGetMessageByChatIdRequest() {
        return new GetMessageByChatIdRequest();
    }

    /**
     * Create an instance of {@link GetMessageByChatIdResponse }
     * 
     */
    public GetMessageByChatIdResponse createGetMessageByChatIdResponse() {
        return new GetMessageByChatIdResponse();
    }

}
