//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 01:06:03 PM CEST 
//


package com.example.voziloservice.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idVozilo" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="predjenaKilometraza" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idVozilo",
    "predjenaKilometraza"
})
@XmlRootElement(name = "updateVoziloRequset")
public class UpdateVoziloRequset {

    protected long idVozilo;
    protected double predjenaKilometraza;

    /**
     * Gets the value of the idVozilo property.
     * 
     */
    public long getIdVozilo() {
        return idVozilo;
    }

    /**
     * Sets the value of the idVozilo property.
     * 
     */
    public void setIdVozilo(long value) {
        this.idVozilo = value;
    }

    /**
     * Gets the value of the predjenaKilometraza property.
     * 
     */
    public double getPredjenaKilometraza() {
        return predjenaKilometraza;
    }

    /**
     * Sets the value of the predjenaKilometraza property.
     * 
     */
    public void setPredjenaKilometraza(double value) {
        this.predjenaKilometraza = value;
    }

}
